### PR TITLE
feature/testLambdaVersion -> master

### PR DESCRIPTION
**Pull request by mzroth**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/hw-lambda-api/103)

### CODE REVIEW

**Review by blakemorgan — DISMISSED** [review]
The Terraform plan isn't executing correctly. Not sure if that is related or not.

**Comment by stuft2** [comment]
Is the terraform lock error popping up cause we have two terraform plans running simultaneously? They have different backend keys so I'd expect them to not get locked... Anyway, I think it's safe to merge this even though there's a terraform lock error.

**Comment by mzroth** [comment]
Why is it trying to do two tf plans? The dependabot bumps only look like they are running one tf plan?

**Comment by GaryGSC** [comment]
@mzroth - `prd` and `cpy`. The Dependabot bumps are against `dev`.

**Comment by mzroth** [comment]
should I change it so the one depends on the other to force them to run sequentially and see if that fixes the error?

**Comment by GaryGSC** [comment]
I don't think they depend on each other at all right now. I think someone probably cancelled a deployment or something so the `prd` state lock mutex was claimed and not returned. I believe all we need to do is go into DynamoDB in the AWS account and delete the corresponding lock.


[cpy](https://github.com/byu-oit/hw-lambda-api/blob/master/terraform-iac/cpy/app/main.tf#L6):  
```hcl
key = "hw-lambda-api/prd/app.tfstate"
```
[prd](https://github.com/byu-oit/hw-lambda-api/blob/master/terraform-iac/prd/app/main.tf#L6):
```hcl
key = "hw-lambda-api/prd/app.tfstate"
```

To help avoid this in the future, we should probably [stop canceling the TF jobs if another TF job fails](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast).

**Comment by GaryGSC** [comment]
You'll note that in #105, **Terraform Plan** for `prd` failed, just like it did here. But over there, `cpy` succeeded instead of getting canceled.

I'm going to go ahead and release the state lock for `prd`. I'm pretty sure it's stuck. Then we can re-run CI.

**Comment by GaryGSC** [comment]
The `prd` state lock had been checked out since `2020-12-22T20:38:09.245039166Z`. 😅

**Comment by GaryGSC** [comment]
@mzroth CI is passing now.

**Comment by mzroth** [comment]
Sweet thanks! Can I get a review check on this again. So I can merge it?

**Review by GaryGSC — COMMENTED** [review]
Umm, my code review probably belongs over in https://github.com/byu-oit/terraform-aws-postman-test-lambda/pull/23, and frankly, I'm not convinced I know what we're trying to accomplish with that PR. To me, it looks like a way to bypass tests. They "pass" as long as `event.Combined` is passed in as something truthy, but in the new case the Lambda no longer updates the CodeDeploy deployment and now the Lambda returns `{ passed: true/false }` based on if the Lambda could locate the collection and environment?

Can you explain more about what you're trying to do?

Earlier, I just focused on getting CI to work as expected.

**Comment by mzroth** [comment]
@GaryGSC 
Yeah no problem. 
Context: Codedeploy (afaik) only lets us call one lambda per lifecycle hook. So If we want to run postman tests and other tests (like UI tests of the front end to make sure backend changes didn't affect app functionality) we needed a parent lambda that can call the postman lambda (I'm writing that) but the postman lambda needed a bit of a fix so that it would pass back a result to the parent lambda. In this case the parent wouldn't pass a deploymentId because it wants the parent to update codedeploy (so tests don't get skipped) so when the parent calls deploymentId will always be falsey. But in that instance I will pass a Combined parameter to the lambda instead.

**Comment by mzroth** [comment]
error also get overriden if the postman tests fail. so it's passing back the results of the tests essentially.

**Comment by GaryGSC** [comment]
> error also get overriden if the postman tests fail. so it's passing back the results of the tests essentially.

Oh, gotcha. I missed that.

**Review by GaryGSC — APPROVED** [review]

**Comment by GaryGSC** [comment]
That awkward moment when I realize I'm the one that green-lit merging directly into `master`.

**Pull request merged**
