### PR TITLE
dev -> stg

### PR DESCRIPTION
**Pull request by yoshutch**

### CODE REVIEW

**Review by stuft2 — APPROVED** [review]

**Comment by yoshutch** [comment]
@jvisker brought up a good question (in person) related to this. Automerging PRs that pass all ci checks makes sense if it's only merging to dev. We're hesitant to automerge into production. The automerging action should only merge if the user was dependabot. And we _should_ have only dependabot make PRs to `dev`, but it's possible to change that per repo and what about security alert PRs, do they go to the default branch or to whatever is defined in the dependabot config?

Thoughts? Should we put an explicit "if target branch is dev then run this automerge job" ?

**Comment by stuft2** [comment]
Does this change mean that dependencies are updated after running tests? I think it should run before the tests so that our tests can catch any regressions.

**Comment by yoshutch** [comment]
> Does this change mean that dependencies are updated after running tests? I think it should run before the tests so that our tests can catch any regressions.

@stuft2 true. But there might be some circumstances that we need to wait to release a change to production, and I think we just want to make sure that we don't accidentally release to production when we don't mean to. I can also see a dependabot update terraform version that passes the ci checks, but when actually trying to apply the new infrastructure it fails and the terraform is now in a weird state. If that happened automatically to our production branch, we wouldn't really know unless a user told us and made an incident.

**Comment by stuft2** [comment]
> I think we just want to make sure that we don't accidentally release to production when we don't mean to.

Yes we shouldn't be automatically merging Dependabot PRs into production so we could be extra cautious by checking the branch. My comment was a bit off-topic.

**Review by GaryGSC — APPROVED** [review]

**Pull request merged**
